package com.example.springbootfirst.mapper;

import com.example.springbootfirst.model.Shopcart;

public interface ShopcartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    int insert(Shopcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    int insertSelective(Shopcart record);

    Shopcart queryBookNum(int bookNum);

    int updateShopcartByOne(Shopcart shopcart);

    int updateShopcart(Shopcart shopcart);

    int delShopcart(Shopcart shopcart);
}