package com.example.springbootfirst.mapper;

import com.example.springbootfirst.model.User;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(User record);


    User selectUserForLogin(@Param("loginName")String loginName, @Param("loginPwd")String loginPwd);
}