package com.example.springbootfirst.model;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_num
     *
     * @mbggenerated
     */
    private Integer bookNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_title
     *
     * @mbggenerated
     */
    private String bookTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_info
     *
     * @mbggenerated
     */
    private String bookInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_price
     *
     * @mbggenerated
     */
    private Integer bookPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_stock
     *
     * @mbggenerated
     */
    private Integer bookStock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_num
     *
     * @return the value of book.book_num
     *
     * @mbggenerated
     */
    public Integer getBookNum() {
        return bookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_num
     *
     * @param bookNum the value for book.book_num
     *
     * @mbggenerated
     */
    public void setBookNum(Integer bookNum) {
        this.bookNum = bookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_title
     *
     * @return the value of book.book_title
     *
     * @mbggenerated
     */
    public String getBookTitle() {
        return bookTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_title
     *
     * @param bookTitle the value for book.book_title
     *
     * @mbggenerated
     */
    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle == null ? null : bookTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_info
     *
     * @return the value of book.book_info
     *
     * @mbggenerated
     */
    public String getBookInfo() {
        return bookInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_info
     *
     * @param bookInfo the value for book.book_info
     *
     * @mbggenerated
     */
    public void setBookInfo(String bookInfo) {
        this.bookInfo = bookInfo == null ? null : bookInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_price
     *
     * @return the value of book.book_price
     *
     * @mbggenerated
     */
    public Integer getBookPrice() {
        return bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_price
     *
     * @param bookPrice the value for book.book_price
     *
     * @mbggenerated
     */
    public void setBookPrice(Integer bookPrice) {
        this.bookPrice = bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_stock
     *
     * @return the value of book.book_stock
     *
     * @mbggenerated
     */
    public Integer getBookStock() {
        return bookStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_stock
     *
     * @param bookStock the value for book.book_stock
     *
     * @mbggenerated
     */
    public void setBookStock(Integer bookStock) {
        this.bookStock = bookStock;
    }
}